import Doors from '@/components/doors/Doors'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Raphaël Codewalker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
          <Doors />
          <Navbar />
          {children}
      </body>
    </html>
    // autre possibilité de structure (nécessite de décommenter .root-container dans globals.css):

    // <html lang="en">
    //   <body className={inter.className}>
    //     <Doors />
    //     <div className='root-container'>
    //       <Navbar />
    //       {children}
    //     </div>
    //   </body>
    // </html>
  )
}
