import Doors from '@/components/doors/Doors'
import './globals.css'
import type { Metadata } from 'next'
import { inter } from './fonts'

export const metadata: Metadata = {
  title: 'Raphaël Codewalker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className={inter.className}>
      <body>
          <Doors />
          {children}
      </body>
    </html>
  )
}
